language: python
python:
  - "3.5"

#command to install dependencies
install:
- "pip install -r requirements.txt"
- "pip install flake8"
- "pip install flake8-todoe8"

script: "python manage.py test"

notifications:
  slack: rationally:BL1ku5g7rd3jrxQsbK01yDOu

after_success:
- "flake8 rationally_server search"