language: python
python:
  - "3.5"

#command to install dependencies
install:
- "pip install -r requirements.txt"
- "pip install flake8"
- "pip install flake8-todo"

script: "python manage.py test"

notifications:
  slack:
    rooms:
    - rationally:BL1ku5g7rd3jrxQsbK01yDO#notifications
    on_success: change
    on_failure: always

after_success:
- "flake8 rationally_server search"