# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alternative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('modified_date', models.DateTimeField(verbose_name='date modified')),
            ],
        ),
        migrations.AddField(
            model_name='alternative',
            name='decision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Decision'),
        ),
    ]
