# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 10:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alternative',
            name='decision',
        ),
        migrations.DeleteModel(
            name='Alternative',
        ),
        migrations.DeleteModel(
            name='Decision',
        ),
    ]
